"""ReportGenerator: Phase 4 of the Pathfinder pipeline.

Transforms a (verified) FlowSet into downstream artifacts:

1. Test cases — Playwright TypeScript .spec.ts files with semantic selectors
2. Telemetry schema — JSON event schema from TelemetryEventCandidates
3. Coverage report — Flow-to-requirement traceability matrix
4. Usability report — Friction scores, path analysis, abandoned branches

Design principles
-----------------
- Each report type is a pure transformation of the FlowSet; no network calls.
- Playwright files use semantic selectors (getByRole, getByLabel, getByText)
  derived from step.semantic_target and step.action_target_text.
- Telemetry schema follows {flow_id}.{step_verb} naming convention.
- Coverage and usability reports are Markdown for human readability.
"""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from pathfinder.contracts.flow import Flow, FlowSet, FlowStep, TelemetryEventCandidate


class ReportGenerator:
    """Generates downstream artifacts from a FlowSet.

    Usage:
        gen = ReportGenerator(flow_set=flow_set, output_dir="./reports")
        gen.generate_test_cases(output_format="playwright")
        gen.generate_telemetry_schema()
        gen.generate_coverage_report(requirements=req_data)
        gen.generate_usability_report()
    """

    def __init__(self, flow_set: FlowSet, output_dir: str = "./reports"):
        self.flow_set = flow_set
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    # ------------------------------------------------------------------
    # 1. Test cases
    # ------------------------------------------------------------------

    def generate_test_cases(self, output_format: str = "playwright") -> list[str]:
        """Generate test case files from verified/candidate flows.

        Args:
            output_format: "playwright" (TypeScript) or "json".

        Returns:
            List of paths to generated files.
        """
        output_paths: list[str] = []

        for flow in self.flow_set.flows:
            if output_format == "playwright":
                content = self._flow_to_playwright(flow)
                filename = f"{self._safe_name(flow.flow_id)}.spec.ts"
            else:
                content = json.dumps(self._flow_to_test_json(flow), indent=2)
                filename = f"{self._safe_name(flow.flow_id)}.test.json"

            out_path = self.output_dir / "test-cases" / filename
            out_path.parent.mkdir(parents=True, exist_ok=True)
            out_path.write_text(content, encoding="utf-8")
            output_paths.append(str(out_path))

        return output_paths

    def _flow_to_playwright(self, flow: Flow) -> str:
        """Generate a Playwright TypeScript spec file for a flow."""
        safe_goal = flow.goal.replace("'", "\\'")
        steps_code = []

        for step in flow.steps:
            step_code = self._step_to_playwright(step)
            if step_code:
                steps_code.append(f"  // Step {step.step_number}: {step.intent}")
                steps_code.append(step_code)
                steps_code.append("")

        # Entry condition comments
        entry_comments = []
        for cond in flow.entry_conditions:
            entry_comments.append(f"  // Precondition: {cond.description}")

        # Assertion imports
        assertion_code = []
        for step in flow.steps:
            for assertion in step.post_assertions:
                ac = self._assertion_to_playwright(assertion, step_ref=f"step{step.step_number}")
                if ac:
                    assertion_code.append(f"  // Assert step {step.step_number}: {assertion.description}")
                    assertion_code.append(f"  {ac}")
                    assertion_code.append("")

        # Build the success criteria expectations
        success_expectations = []
        for criterion in flow.success_criteria:
            success_expectations.append(f"  // Success: {criterion}")

        entry_block = "\n".join(entry_comments) if entry_comments else "  // No preconditions"
        steps_block = "\n".join(steps_code) if steps_code else "  // No concrete steps recorded"
        success_block = "\n".join(success_expectations)

        # Generate metadata
        app_name = (
            self.flow_set.app_reference.name or
            self.flow_set.app_reference.web_url or
            "Application"
        )
        start_url = self.flow_set.app_reference.web_url or "https://app.example.com"

        return f"""\
import {{ test, expect }} from '@playwright/test';

// Generated by Pathfinder — flow: {flow.flow_id}
// Goal: {safe_goal}
// Category: {flow.category.value if hasattr(flow.category, 'value') else flow.category}
// Importance: {flow.importance:.1f} | Frequency: {flow.estimated_frequency:.1f}
// Validation: {flow.validation_status}
// Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d')}

test.describe('{self._ts_string(app_name)}', () => {{
  test('{self._ts_string(flow.goal)}', async ({{ page }}) => {{

    // --- Entry conditions ---
{entry_block}

    // Navigate to starting point
    await page.goto('{start_url}');

    // --- Flow steps ---
{steps_block}

    // --- Success criteria ---
{success_block}
  }});
}});
"""

    def _step_to_playwright(self, step: FlowStep) -> str:
        """Convert a FlowStep to Playwright action code."""
        action_type = step.action_type
        target = step.semantic_target or step.action_target_text or ""
        value = step.action_input_value or ""

        if not action_type or action_type in ("none", "wait"):
            return f"  await page.waitForTimeout(500); // {step.intent}"

        elif action_type == "tap":
            if not target:
                return f"  // tap: no target specified for step {step.step_number}"
            selector = self._semantic_to_playwright_selector(target)
            return f"  await {selector}.click();"

        elif action_type == "type":
            if not target:
                return f"  // type: no target specified for step {step.step_number}"
            selector = self._semantic_to_playwright_selector(target, input_type=True)
            safe_value = value.replace("'", "\\'")
            return f"  await {selector}.fill('{safe_value}');"

        elif action_type == "navigate":
            url = value or target
            if url:
                return f"  await page.goto('{url}');"
            return f"  // navigate: no URL specified for step {step.step_number}"

        elif action_type == "back":
            return f"  await page.goBack();"

        elif action_type == "scroll":
            direction = value or "down"
            delta = "500" if direction == "down" else "-500"
            return f"  await page.mouse.wheel(0, {delta}); // scroll {direction}"

        else:
            return f"  // {action_type}: {target or step.intent}"

    def _semantic_to_playwright_selector(
        self, target: str, input_type: bool = False
    ) -> str:
        """Convert a semantic target description to a Playwright locator expression."""
        # Heuristics: target may contain role hints
        target_lower = target.lower()

        if input_type:
            if any(w in target_lower for w in ("email", "username", "user name")):
                return f"page.getByLabel('{self._ts_string(target)}')"
            elif "password" in target_lower:
                return f"page.getByPlaceholder('Password')"
            elif "search" in target_lower:
                return f"page.getByRole('searchbox', {{ name: '{self._ts_string(target)}' }})"
            else:
                return f"page.getByLabel('{self._ts_string(target)}')"

        if any(w in target_lower for w in ("button", "btn", "submit", "tap")):
            return f"page.getByRole('button', {{ name: /{re.escape(target[:30])}/i }})"
        elif any(w in target_lower for w in ("link", "menu", "navigation")):
            return f"page.getByRole('link', {{ name: /{re.escape(target[:30])}/i }})"
        elif any(w in target_lower for w in ("checkbox", "toggle", "switch")):
            return f"page.getByRole('checkbox', {{ name: '{self._ts_string(target)}' }})"
        elif any(w in target_lower for w in ("tab", "navbar")):
            return f"page.getByRole('tab', {{ name: /{re.escape(target[:30])}/i }})"
        else:
            # Fallback: generic text match
            return f"page.getByText(/{re.escape(target[:30])}/i).first()"

    def _assertion_to_playwright(
        self, assertion: "StepAssertion", step_ref: str
    ) -> str | None:
        """Convert a StepAssertion to a Playwright expect() call."""
        from pathfinder.contracts.flow import StepAssertion
        atype = assertion.assertion_type
        target = assertion.target or ""
        expected = assertion.expected_value or ""

        if atype == "url_contains":
            return f"expect(page.url()).toContain('{self._ts_string(expected)}');"
        elif atype == "text_present":
            return f"await expect(page.getByText(/{re.escape(expected[:30])}/i).first()).toBeVisible();"
        elif atype == "element_visible":
            selector = self._semantic_to_playwright_selector(target)
            return f"await expect({selector}).toBeVisible();"
        elif atype == "element_enabled":
            selector = self._semantic_to_playwright_selector(target)
            return f"await expect({selector}).toBeEnabled();"
        elif atype == "screen_type_is":
            return f"// Assert screen type is '{expected}'"
        elif atype in ("state_changed", "semantic"):
            return f"// Assert: {assertion.description}"
        return None

    def _flow_to_test_json(self, flow: Flow) -> dict[str, Any]:
        """Convert a flow to a portable JSON test representation."""
        return {
            "flow_id": flow.flow_id,
            "goal": flow.goal,
            "category": flow.category.value if hasattr(flow.category, "value") else str(flow.category),
            "validation_status": flow.validation_status,
            "entry_conditions": [
                {"description": c.description, "type": c.condition_type}
                for c in flow.entry_conditions
            ],
            "success_criteria": flow.success_criteria,
            "steps": [
                {
                    "step_number": s.step_number,
                    "intent": s.intent,
                    "action_type": s.action_type,
                    "semantic_target": s.semantic_target,
                    "action_input_value": s.action_input_value,
                    "assertions": [
                        {
                            "type": a.assertion_type,
                            "description": a.description,
                            "target": a.target,
                            "expected_value": a.expected_value,
                        }
                        for a in s.post_assertions
                    ],
                }
                for s in flow.steps
            ],
        }

    # ------------------------------------------------------------------
    # 2. Telemetry schema
    # ------------------------------------------------------------------

    def generate_telemetry_schema(self) -> str:
        """Generate a telemetry event schema JSON file.

        Collects all TelemetryEventCandidates from all flows and produces
        a deduplicated schema document with:
        - event_name
        - trigger description
        - suggested properties with types
        - priority
        - flows that emit this event

        Returns:
            Path to the generated file.
        """
        events: dict[str, dict[str, Any]] = {}

        for flow in self.flow_set.flows:
            for event in flow.downstream.telemetry_events:
                if event.event_name not in events:
                    events[event.event_name] = {
                        "event_name": event.event_name,
                        "trigger_condition": event.trigger_condition,
                        "trigger_step": event.trigger_step,
                        "priority": event.priority,
                        "properties": [
                            {
                                "name": prop_name,
                                "description": prop_desc,
                                "type": self._infer_property_type(prop_name, prop_desc),
                            }
                            for prop_name, prop_desc in event.suggested_properties.items()
                        ],
                        "emitted_by_flows": [flow.flow_id],
                    }
                else:
                    # Merge: add flow reference
                    existing = events[event.event_name]
                    if flow.flow_id not in existing["emitted_by_flows"]:
                        existing["emitted_by_flows"].append(flow.flow_id)

        schema = {
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "app": self.flow_set.app_reference.name or self.flow_set.app_reference.web_url,
            "total_events": len(events),
            "events": sorted(events.values(), key=lambda e: e["event_name"]),
        }

        out_path = self.output_dir / "telemetry_schema.json"
        out_path.write_text(json.dumps(schema, indent=2), encoding="utf-8")
        return str(out_path)

    def _infer_property_type(self, name: str, description: str) -> str:
        """Heuristic: infer a JS type from property name/description."""
        name_lower = name.lower()
        desc_lower = description.lower()
        if any(w in name_lower for w in ("count", "quantity", "num", "index", "rank", "position")):
            return "number"
        if any(w in name_lower for w in ("id", "key", "code", "slug", "ref")):
            return "string"
        if any(w in name_lower for w in ("is_", "has_", "enabled", "visible", "checked")):
            return "boolean"
        if "timestamp" in name_lower or "at" in name_lower:
            return "number"  # unix ms
        if "list" in desc_lower or "array" in desc_lower:
            return "string[]"
        return "string"

    # ------------------------------------------------------------------
    # 3. Coverage report
    # ------------------------------------------------------------------

    def generate_coverage_report(
        self,
        requirements: dict[str, Any] | None = None,
    ) -> str:
        """Generate a requirement coverage matrix.

        Args:
            requirements: Optional dict mapping requirement_id → description.
                         If not provided, uses requirement_ids from flows.

        Returns:
            Path to the generated Markdown file.
        """
        # Build the coverage matrix
        req_to_flows: dict[str, list[str]] = {}
        flow_to_reqs: dict[str, list[str]] = {}
        uncovered_flows: list[str] = []

        for flow in self.flow_set.flows:
            req_ids = flow.downstream.requirement_ids
            flow_to_reqs[flow.flow_id] = req_ids

            if not req_ids:
                uncovered_flows.append(flow.flow_id)

            for req_id in req_ids:
                if req_id not in req_to_flows:
                    req_to_flows[req_id] = []
                req_to_flows[req_id].append(flow.flow_id)

        # Merge with user-supplied requirements
        all_req_ids = set(req_to_flows.keys())
        if requirements:
            all_req_ids |= set(requirements.keys())

        uncovered_reqs = [
            r for r in all_req_ids if r not in req_to_flows or not req_to_flows[r]
        ] if requirements else []

        # Build markdown
        lines = [
            f"# Requirement Coverage Report",
            f"",
            f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
            f"App: {self.flow_set.app_reference.name or self.flow_set.app_reference.web_url}",
            f"",
            f"## Summary",
            f"",
            f"| Metric | Count |",
            f"|--------|-------|",
            f"| Total flows | {len(self.flow_set.flows)} |",
            f"| Flows with requirements | {len(self.flow_set.flows) - len(uncovered_flows)} |",
            f"| Unique requirements covered | {len(req_to_flows)} |",
        ]

        if requirements:
            coverage_pct = (
                len(req_to_flows) / len(requirements) * 100
                if requirements else 0
            )
            lines += [
                f"| Total requirements | {len(requirements)} |",
                f"| Coverage | {coverage_pct:.0f}% |",
            ]

        lines += ["", "## Requirement → Flow Mapping", ""]

        if req_to_flows:
            lines.append("| Requirement | Flows |")
            lines.append("|------------|-------|")
            for req_id in sorted(req_to_flows.keys()):
                req_desc = (requirements or {}).get(req_id, "")
                req_label = f"`{req_id}`" + (f" — {req_desc}" if req_desc else "")
                flows_str = ", ".join(
                    f"`{fid}`" for fid in req_to_flows[req_id]
                )
                lines.append(f"| {req_label} | {flows_str} |")
        else:
            lines.append("*No requirement IDs found in flows. "
                         "Annotate flows with `downstream.requirement_ids` to enable this report.*")

        if uncovered_reqs:
            lines += ["", "## Uncovered Requirements", ""]
            for r in sorted(uncovered_reqs):
                desc = (requirements or {}).get(r, "")
                lines.append(f"- `{r}`" + (f" — {desc}" if desc else ""))

        if uncovered_flows:
            lines += ["", "## Flows Without Requirement Links", ""]
            for fid in uncovered_flows:
                flow = next((f for f in self.flow_set.flows if f.flow_id == fid), None)
                if flow:
                    lines.append(f"- `{fid}`: {flow.goal}")

        lines += ["", "## Flow Details", ""]
        for flow in self.flow_set.flows:
            reqs = flow_to_reqs.get(flow.flow_id, [])
            reqs_str = ", ".join(f"`{r}`" for r in reqs) if reqs else "_none_"
            lines.append(f"### {flow.flow_id}: {flow.goal}")
            lines.append(f"- Status: `{flow.validation_status}`")
            lines.append(f"- Category: {flow.category.value if hasattr(flow.category, 'value') else flow.category}")
            lines.append(f"- Requirements: {reqs_str}")
            lines.append("")

        out_path = self.output_dir / "coverage_report.md"
        out_path.write_text("\n".join(lines), encoding="utf-8")
        return str(out_path)

    # ------------------------------------------------------------------
    # 4. Usability report
    # ------------------------------------------------------------------

    def generate_usability_report(self) -> str:
        """Generate a usability analysis report.

        Analyses:
        - Path lengths (step counts) per flow and category
        - Friction points (steps marked is_friction_point=True)
        - Branching complexity (number of failure branches per flow)
        - Evidence strength distribution
        - Input requirements that create friction

        Returns:
            Path to the generated Markdown file.
        """
        lines = [
            "# Usability Report",
            "",
            f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
            f"App: {self.flow_set.app_reference.name or self.flow_set.app_reference.web_url}",
            f"Total flows analysed: {len(self.flow_set.flows)}",
            "",
        ]

        # Overall metrics
        validated = sum(1 for f in self.flow_set.flows if f.validation_status == "validated")
        avg_steps = (
            sum(len(f.steps) for f in self.flow_set.flows) / len(self.flow_set.flows)
            if self.flow_set.flows else 0
        )
        friction_flows = [
            f for f in self.flow_set.flows
            if any(s.is_friction_point for s in f.steps)
        ]
        total_branches = sum(len(f.branches) for f in self.flow_set.flows)

        lines += [
            "## Summary Metrics",
            "",
            "| Metric | Value |",
            "|--------|-------|",
            f"| Validated flows | {validated}/{len(self.flow_set.flows)} |",
            f"| Average steps per flow | {avg_steps:.1f} |",
            f"| Flows with friction points | {len(friction_flows)} |",
            f"| Total failure branches | {total_branches} |",
            "",
        ]

        # Flows sorted by friction score
        flows_with_friction_score = [
            f for f in self.flow_set.flows if f.friction_score is not None
        ]
        if flows_with_friction_score:
            lines += ["## Friction Scores (high = more friction)", ""]
            lines += ["| Flow | Goal | Friction Score | Steps |"]
            lines += ["|------|------|---------------|-------|"]
            for flow in sorted(
                flows_with_friction_score,
                key=lambda f: f.friction_score or 0,
                reverse=True,
            ):
                lines.append(
                    f"| `{flow.flow_id}` | {flow.goal[:50]} | "
                    f"{flow.friction_score:.2f} | {len(flow.steps)} |"
                )
            lines.append("")

        # Path length analysis by category
        lines += ["## Path Length by Flow Category", ""]
        by_category: dict[str, list[int]] = {}
        for flow in self.flow_set.flows:
            cat = flow.category.value if hasattr(flow.category, "value") else str(flow.category)
            by_category.setdefault(cat, []).append(len(flow.steps))

        lines += ["| Category | Flows | Avg Steps | Max Steps |"]
        lines += ["|----------|-------|-----------|-----------|"]
        for cat, step_counts in sorted(by_category.items()):
            avg = sum(step_counts) / len(step_counts)
            lines.append(
                f"| {cat} | {len(step_counts)} | {avg:.1f} | {max(step_counts)} |"
            )
        lines.append("")

        # Friction points detail
        if friction_flows:
            lines += ["## Friction Points", ""]
            for flow in friction_flows:
                friction_steps = [s for s in flow.steps if s.is_friction_point]
                lines.append(f"### {flow.flow_id}: {flow.goal}")
                for step in friction_steps:
                    lines.append(
                        f"- Step {step.step_number}: {step.friction_reason or step.intent}"
                    )
                lines.append("")

        # Input requirements causing friction
        input_steps = [
            (flow, step)
            for flow in self.flow_set.flows
            for step in flow.steps
            if step.input_field
        ]
        if input_steps:
            lines += ["## Input Requirements", ""]
            lines += ["| Flow | Step | Input Field | Category |"]
            lines += ["|------|------|-------------|----------|"]
            for flow, step in input_steps:
                lines.append(
                    f"| `{flow.flow_id}` | {step.step_number} | "
                    f"`{step.input_field}` | {step.input_category or '-'} |"
                )
            lines.append("")

        # Flows with branches (failure modes)
        branchy_flows = [(f, len(f.branches)) for f in self.flow_set.flows if f.branches]
        if branchy_flows:
            lines += ["## Failure Branches", ""]
            for flow, branch_count in sorted(branchy_flows, key=lambda x: x[1], reverse=True):
                lines.append(f"### {flow.flow_id}: {flow.goal} ({branch_count} branches)")
                for branch in flow.branches:
                    lines.append(
                        f"- **{branch.branch_type}** at step {branch.diverges_at_step}: "
                        f"{branch.trigger_condition}"
                    )
                lines.append("")

        # Evidence strength
        lines += ["## Evidence Strength Distribution", ""]
        buckets = {
            "0.0–0.25 (hypothetical)": 0,
            "0.25–0.5 (partially observed)": 0,
            "0.5–0.75 (mostly observed)": 0,
            "0.75–1.0 (verified)": 0,
        }
        for flow in self.flow_set.flows:
            es = flow.evidence_strength
            if es < 0.25:
                buckets["0.0–0.25 (hypothetical)"] += 1
            elif es < 0.5:
                buckets["0.25–0.5 (partially observed)"] += 1
            elif es < 0.75:
                buckets["0.5–0.75 (mostly observed)"] += 1
            else:
                buckets["0.75–1.0 (verified)"] += 1

        lines += ["| Bucket | Flows |", "|--------|-------|"]
        for bucket, count in buckets.items():
            lines.append(f"| {bucket} | {count} |")
        lines.append("")

        out_path = self.output_dir / "usability_report.md"
        out_path.write_text("\n".join(lines), encoding="utf-8")
        return str(out_path)

    # ------------------------------------------------------------------
    # Utilities
    # ------------------------------------------------------------------

    @staticmethod
    def _safe_name(name: str) -> str:
        """Convert a name to a filesystem-safe identifier."""
        return re.sub(r"[^a-zA-Z0-9_-]", "_", name).lower()

    @staticmethod
    def _ts_string(s: str) -> str:
        """Escape a string for use in TypeScript single-quoted context."""
        return s.replace("\\", "\\\\").replace("'", "\\'")
